language: node_js
sudo: required
node_js:
  - 10
  - 12
  - 14
addons:
  apt:
    sources:
      # gcc 4.8+ requires ubuntu-toolchain-r-test
      - ubuntu-toolchain-r-test
    packages:
      # NodeJS v4+ requires gcc 4.8+
      - g++-4.9
      - gcc-4.9
env:
  global:
    # NodeJS v4+ requires gcc 4.8+
    - CXX=g++-4.9 CC=gcc-4.9
    - TRAVIS=true
script: npm test
after_script: make test-coveralls
